//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aptekaaa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekarstvo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Forma { get; set; }
        public string Doza { get; set; }
        public string Proiz { get; set; }
        public string Srok { get; set; }
    }
}
